# "REST Client" from Exensions

@baseUri=http://127.0.0.1:5050

### root
GET {{baseUri}}/

### blueprint
GET {{baseUri}}/blueprint/bluehello
Content-Type: application/json

### Get add smile
GET {{baseUri}}/blueprint/smile

### Post add smil
POST {{baseUri}}/blueprint/smile
Content-Type: application/json

{
    "msg": "i get a text?"
}


