# "REST Client" from Exensions
# 记得安装 “ REST Client ” 插件

# @baseUri=http://localhost:3000 
@baseUri=http://127.0.0.1:5000 

### root - app
GET {{baseUri}}/

### get - app
GET {{baseUri}}/get

### post - app
POST {{baseUri}}/post
Content-Type: application/json

{
  "msg": "hello? couly you get it?"
}


### double get - app
GET {{baseUri}}/double

### double post - app
POST {{baseUri}}/double
Content-Type: application/json

{
  "msg": "a post for doule"
}

### Blueprint - blueprint
GET {{baseUri}}/blueprint/

### Blueprint - g - blueprint
GET {{baseUri}}/blueprint/g

### lib
GET {{baseUri}}/lib
